name: Build Example

on:
  workflow_dispatch:

jobs:
  dependencies-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: build the code
        run: |
          npm run build --if-present
          zip -r app_bundle.zip . -x "*.git*" "app_bundle.zip"
          
      - name: test he code
        run: npm test -- --coverage

      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1.7.0
        with:
          coverage-file: coverage/lcov.info
